from __future__ import annotations

import json
from pathlib import Path
from typing import Dict, List, Set


DEFAULT_NETFILE = Path("tap-b/net/SiouxFalls_net.txt")
DEFAULT_BUS_LOCATION = Path("bus_location.json")
DEFAULT_CRITICAL_DESTINATIONS = [1, 24]

OUT_NODE_TO_ZONE = Path("taskB_node_to_zone.json")
OUT_BUS_TO_ZONE = Path("taskB_bus_to_zone.json")
OUT_CRITICAL = Path("critical_location.json")
OUT_LEGACY_DEST = Path("taskB_essential_destinations.json")
OUT_ASSUMP = Path("TASKB_ASSUMPTIONS.md")


def parse_nodes_from_tap_net(netfile: Path) -> List[int]:
    if not netfile.exists():
        raise FileNotFoundError(f"Network file not found: {netfile}")

    nodes: Set[int] = set()
    with netfile.open("r", encoding="utf-8") as f:
        for line in f:
            s = line.strip()
            if not s or s.startswith("~") or s.startswith(";"):
                continue
            parts = s.split()
            if len(parts) < 2:
                continue
            try:
                u = int(parts[0])
                v = int(parts[1])
            except Exception:
                continue
            nodes.add(u)
            nodes.add(v)

    if not nodes:
        raise RuntimeError(f"No nodes parsed from {netfile}. Check file format.")
    return sorted(nodes)


def load_bus_location(path: Path) -> Dict[int, int]:
    if not path.exists():
        raise FileNotFoundError(f"bus_location.json not found: {path}")
    raw = json.loads(path.read_text(encoding="utf-8"))
    out: Dict[int, int] = {}
    if isinstance(raw, dict):
        for k, v in raw.items():
            out[int(k)] = int(v)
    if not out:
        raise RuntimeError(f"Failed to load mappings from {path}")
    return out


def write_json(path: Path, obj: object) -> None:
    path.write_text(json.dumps(obj, indent=2, sort_keys=True), encoding="utf-8")


def generate_taskb_inputs(destinations: List[int] | None = None) -> Dict[str, object]:
    nodes = parse_nodes_from_tap_net(DEFAULT_NETFILE)
    dest = list(DEFAULT_CRITICAL_DESTINATIONS if destinations is None else destinations)
    bad_dest = [int(d) for d in dest if int(d) not in nodes]
    if bad_dest:
        raise ValueError(f"Critical destinations must be network nodes. Invalid: {bad_dest}")

    # 1) node -> zone (identity)
    node_to_zone = {str(n): int(n) for n in nodes}
    write_json(OUT_NODE_TO_ZONE, node_to_zone)

    # 2) bus -> zone via bus_location (zone==node)
    bus_loc = load_bus_location(DEFAULT_BUS_LOCATION)
    bus_to_zone = {str(b): int(node) for b, node in bus_loc.items()}
    write_json(OUT_BUS_TO_ZONE, bus_to_zone)

    # 3) critical destinations: deterministic placeholder nodes
    critical_obj = {
        "description": "Deterministic critical locations used for Task B accessibility placeholder.",
        "destinations": dest,
    }
    write_json(OUT_CRITICAL, critical_obj)
    write_json(OUT_LEGACY_DEST, critical_obj)

    # 4) assumptions note
    OUT_ASSUMP.write_text(
        f"""# Task B (Equity / CRI) – Current Working Assumptions

Generated by `taskB_setup.py`.

## Mapping assumptions (temporary, for fast data generation)
1) **Zones**: each transportation node is treated as its own zone.
   - File: `{OUT_NODE_TO_ZONE.name}`
   - Mapping rule: zone_id = node_id

2) **Bus-to-zone mapping**: each power bus is assigned to a zone using `bus_location.json`.
   - File: `{OUT_BUS_TO_ZONE.name}`
   - Current rule: bus -> node from `bus_location.json`, then zone = node (because zone==node).

2b) **Crew dispatch mapping** (current experiment setting):
   - Uses `new_bus_to_link.json` as the primary bus-to-road mapping for dispatch and road interdependency
   - Current runner/tradeoff default: `bus_dispatch_mode = link_only`
   - `bus_location.json` is retained mainly for zone mapping and legacy compatibility

3) **Critical locations** (placeholder, deterministic):
   - Primary file: `{OUT_CRITICAL.name}`
   - Legacy compatibility file: `{OUT_LEGACY_DEST.name}`
   - Current selection: {dest}

## CRI definition (current implementation)
Let zone z correspond to node z.

1) Electric component E_z(t):
   - Fraction of functional buses located in zone z.
   - Functional buses from `get_functional_nodes(broken_buses)`.

2) Accessibility component A_z(t):
   - Uses shortest-path travel time on current TAP-B output `s.txt`.
   - Let TT_z(t) = min distance from zone node z to any critical location.
   - Baseline TT_z^0 is computed in the original (no-disruption) state.
   - A_z(t) = min(1, TT_z^0 / TT_z(t)).

3) CRI:
   - CRI_z(t) = w_e * E_z(t) + w_a * A_z(t)
   - The implementation now supports sensitivity scans over `w_e`, `w_a`, CRI threshold, and critical-access threshold.

4) Critical-access status:
   - A zone is counted as having restored critical access once A_z(t) reaches the configured threshold.
   - The code reports restoration-time summaries such as `p90_access_restore`.

## Where to modify later
- Zones: replace `{OUT_NODE_TO_ZONE.name}`
- Bus mapping: replace `{OUT_BUS_TO_ZONE.name}` (or regenerate from a different bus-location dataset)
- Dispatch mapping: replace `new_bus_to_link.json` or change `bus_dispatch_mode`
- Critical locations: replace `{OUT_CRITICAL.name}`
- CRI weights / thresholds: see `resilience_measurement.py` and `tradeoff_runner.py`

""",
        encoding="utf-8",
    )

    return {
        "node_to_zone_path": str(OUT_NODE_TO_ZONE),
        "bus_to_zone_path": str(OUT_BUS_TO_ZONE),
        "critical_location_path": str(OUT_CRITICAL),
        "legacy_destination_path": str(OUT_LEGACY_DEST),
        "destinations": dest,
    }


def main() -> None:
    info = generate_taskb_inputs()
    print("Generated:")
    print(f"  - {info['node_to_zone_path']}")
    print(f"  - {info['bus_to_zone_path']}")
    print(f"  - {info['critical_location_path']}")
    print(f"  - {info['legacy_destination_path']}")
    print(f"  - {OUT_ASSUMP}")


if __name__ == "__main__":
    main()
