#!/usr/bin/env python3
"""Offline geographical QA view with source node coordinates and schematic link chords."""
import csv,gzip,json
from pathlib import Path
from build_dataset import ROOT,OUT

def rows(path):
    with (gzip.open(path,'rt') if path.suffix=='.gz' else path.open()) as f:return list(csv.DictReader(f))

signals=[r for r in rows(OUT/'signals/inventory.csv') if r['use_in_v0']=='1']
matches={r['signal_id']:r for r in rows(OUT/'coupling/signal_power_candidates.csv') if r['candidate_rank']=='1'}
substations=rows(OUT/'power/distribution_v03/substations.csv')
needed={r['load_id'] for r in matches.values()}
with gzip.open(OUT/'power/distribution_v03/loads.csv.gz','rt') as f:
    locations={r['load_id']:[float(r['longitude']),float(r['latitude'])] for r in csv.DictReader(f) if r['load_id'] in needed}
road_nodes=rows(OUT/'road/nodes.csv')
road_links=rows(OUT/'road/links.csv')
road_matches={r['signal_id']:r for r in rows(OUT/'coupling/signal_road_candidates.csv') if r['candidate_rank']=='1'}
node_coords={r['node_id']:[float(r['longitude']),float(r['latitude'])] for r in road_nodes}
data={'nodes':{r['node_id']:[*node_coords[r['node_id']],r['node_type']] for r in road_nodes},'links':[[r['link_id'],r['from_node'],r['to_node'],int(r['centroid_connector'])] for r in road_links], 'signals':[dict(id=r['signal_id'],road_node=r['road_node_id'],road_status=r['road_match_status'],road_candidate=road_matches[r['signal_id']]['road_node_id'],road_distance=float(road_matches[r['signal_id']]['distance_m']),road_point=node_coords[road_matches[r['signal_id']]['road_node_id']],name=r['name'],lon=float(r['longitude']),lat=float(r['latitude']),feeder=matches[r['signal_id']]['feeder_id'],substation=matches[r['signal_id']]['substation_id'],distance=float(matches[r['signal_id']]['distance_m']),point=locations[matches[r['signal_id']]['load_id']],load=matches[r['signal_id']]['load_id']) for r in signals], 'substations':[dict(id=r['Name'],lon=float(r['Longitude']),lat=float(r['Latitude']),mw=float(r['Total Real Load'])/1e6) for r in substations]}
html='''<!doctype html><html lang="zh"><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Austin v1 路网、电网与信号灯</title><style>
*{box-sizing:border-box}body{margin:0;background:#f5f7fb;color:#183149;font:15px system-ui,"Microsoft Yahei",sans-serif}header{background:#142d43;color:white;padding:22px 30px}h1{font-size:24px;margin:0 0 8px}header p{margin:0;color:#d1e0ec}main{display:grid;grid-template-columns:1fr 320px;height:calc(100vh - 105px)}section{position:relative;padding:15px}canvas{width:100%;height:100%;border:1px solid #cedae6;background:#fff;touch-action:none}aside{padding:22px;overflow:auto;border-left:1px solid #d5dfe8;background:white}button,input{font:inherit}button{padding:6px 12px;border:1px solid #bbcbd8;border-radius:5px;background:white;cursor:pointer}label{display:block;margin:12px 0}.blue{color:#1674ac}.orange{color:#b55b08}.green{color:#16815d}#detail{white-space:pre-wrap;line-height:1.7;font-size:14px}.hint{color:#607386;font-size:13px;line-height:1.7}.controls{position:absolute;top:25px;left:25px;display:flex;gap:8px}@media(max-width:800px){main{grid-template-columns:1fr;height:auto}section{height:65vh}aside{border:0}}
</style><header><h1>Austin · 路网、电网与信号灯 v1</h1><p>7,466 个来源坐标节点 · 18,710 条有向链接 · TAP-B Austin_sdb</p></header><main><section><canvas id="map"></canvas><div class="controls"><button id="fit">全图</button><button id="city">Austin 城区</button><button id="plus">＋</button><button id="minus">－</button></div></section><aside><strong id="counts"></strong><label><input id="roads" type="checkbox" checked> 灰线：模型道路</label><label><input id="centroids" type="checkbox"> 浅灰：分区质心与连接边</label><label><input id="nodes" type="checkbox"> 道路节点（放大查看）</label><label><input id="subs" type="checkbox" checked> <span class="green">■ 128 个配电变电站</span></label><label><input id="good" type="checkbox" checked> <span class="blue">● 200 米内供电候选</span></label><label><input id="bad" type="checkbox" checked> <span class="orange">● 超距未匹配</span></label><label>灯号 / N:节点 <input id="search" style="width:120px" placeholder="844 或 N:4089"></label><button id="locate">定位</button><p class="hint">拖动平移，滚轮缩放，点击信号灯查看候选馈线。选择后蓝虚线连接道路候选，粉虚线连接合成负荷。道路与供电关联均待人工核对。</p><div id="detail">请选择一个信号灯。</div><hr><p class="hint">道路节点来自 TAP_Demand，已与 DSTAP 全表交叉核对；有向链接以端点直线示意，并非道路中心线。原始坐标未声明测地基准。灯控候选规则：50 米内、次近点至少远 20 米、无多灯冲突；电力候选为 200 米内最近合成负荷。供电、进口控制、维修出入口均未实地核验。</p></aside></main><script>
const D=__DATA__;const canvas=document.getElementById('map'),ctx=canvas.getContext('2d');let W,H,cx=-97.77,cy=30.31,scale=1000,selected=null,selectedNode=null,drag=null,moved=false;const cos=Math.cos(30.3*Math.PI/180);
const xy=(lon,lat)=>[W/2+(lon-cx)*scale*cos,H/2-(lat-cy)*scale];
function fit(){const a=[...D.signals,...D.substations,...Object.values(D.nodes).map(n=>({lon:n[0],lat:n[1]}))],xmin=Math.min(...a.map(x=>x.lon)),xmax=Math.max(...a.map(x=>x.lon)),ymin=Math.min(...a.map(x=>x.lat)),ymax=Math.max(...a.map(x=>x.lat));cx=(xmin+xmax)/2;cy=(ymin+ymax)/2;scale=Math.min((W-70)/((xmax-xmin)*cos),(H-60)/(ymax-ymin));draw()}
function draw(){ctx.clearRect(0,0,W,H);ctx.lineWidth=1;ctx.font='11px system-ui';const step=scale>14000?.005:scale>4000?.02:.1;for(let lon=-99;lon<-96;lon+=step){const [x]=xy(lon,cy);if(x<0||x>W)continue;ctx.strokeStyle='#ecf0f5';ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,H);ctx.stroke();ctx.fillStyle='#698092';ctx.fillText(lon.toFixed(3),x+3,H-8)}for(let lat=29;lat<32;lat+=step){const [,y]=xy(cx,lat);if(y<0||y>H)continue;ctx.strokeStyle='#ecf0f5';ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke();ctx.fillStyle='#698092';ctx.fillText(lat.toFixed(3),5,y-4)}if(document.getElementById('roads').checked){ctx.lineWidth=.65;for(const l of D.links){if(l[3]&&!document.getElementById('centroids').checked)continue;const a=xy(...D.nodes[l[1]]),b=xy(...D.nodes[l[2]]);ctx.strokeStyle=l[3]?'#e3e7ec':'#9aaab7';ctx.beginPath();ctx.moveTo(...a);ctx.lineTo(...b);ctx.stroke()}}if(document.getElementById('nodes').checked)for(const [id,n] of Object.entries(D.nodes)){if(n[2]==='centroid'&&!document.getElementById('centroids').checked)continue;const [x,y]=xy(...n);ctx.fillStyle=n[2]==='centroid'?'#9da6b1':'#5c688c';ctx.fillRect(x-1.7,y-1.7,3.4,3.4);if(scale>40000){ctx.font='10px system-ui';ctx.fillText(id,x+3,y-3)}}if(selectedNode){const [x,y]=xy(...D.nodes[selectedNode]);ctx.strokeStyle='#e05222';ctx.lineWidth=2;ctx.beginPath();ctx.arc(x,y,8,0,Math.PI*2);ctx.stroke()}if(document.getElementById('subs').checked)for(const s of D.substations){let [x,y]=xy(s.lon,s.lat);ctx.fillStyle='#16815d';ctx.fillRect(x-3,y-3,6,6)}for(const s of D.signals){const good=s.distance<=200;if(!document.getElementById(good?'good':'bad').checked)continue;let [x,y]=xy(s.lon,s.lat);ctx.fillStyle=good?'#1674ac':'#b55b08';ctx.beginPath();ctx.arc(x,y,s===selected?6:3,0,Math.PI*2);ctx.fill()}if(selected){const a=xy(selected.lon,selected.lat),b=xy(...selected.point);ctx.setLineDash([4,4]);ctx.strokeStyle='#c34279';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(...a);ctx.lineTo(...b);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle='#c34279';ctx.fillRect(b[0]-4,b[1]-4,8,8);const c=xy(...selected.road_point);ctx.strokeStyle='#355de0';ctx.setLineDash([5,3]);ctx.beginPath();ctx.moveTo(...a);ctx.lineTo(...c);ctx.stroke();ctx.setLineDash([]);ctx.strokeRect(c[0]-5,c[1]-5,10,10)}}
function choose(s){selected=s;selectedNode=null;document.getElementById('detail').textContent=`编号：${s.id}\n路口：${s.name}\n最近负荷距离：${s.distance.toFixed(1)} m\n状态：${s.distance<=200?'暂定候选，需审核':'超距，未匹配'}\n馈线：${s.feeder}\n变电站：${s.substation}\n合成负荷：${s.load}\n道路候选：${s.road_candidate}（${s.road_distance.toFixed(1)} m）\n道路状态：${s.road_node?'暂定候选，待审核':s.road_status}\n坐标：${s.lon.toFixed(6)}, ${s.lat.toFixed(6)}\n配时：原始清单未提供`;draw()}
function resize(){W=canvas.clientWidth;H=canvas.clientHeight;let r=window.devicePixelRatio||1;canvas.width=W*r;canvas.height=H*r;ctx.setTransform(r,0,0,r,0,0);draw()}
new ResizeObserver(resize).observe(canvas);document.getElementById('fit').onclick=fit;document.getElementById('city').onclick=()=>{cx=-97.743;cy=30.285;scale=5500;draw()};document.getElementById('plus').onclick=()=>{scale*=1.7;draw()};document.getElementById('minus').onclick=()=>{scale/=1.7;draw()};for(const id of ['subs','good','bad','roads','centroids','nodes'])document.getElementById(id).onchange=draw;document.getElementById('locate').onclick=()=>{const q=document.getElementById('search').value.trim();if(q.toUpperCase().startsWith('N:')){const id=q.slice(2);if(D.nodes[id]){selected=null;selectedNode=id;cx=D.nodes[id][0];cy=D.nodes[id][1];scale=50000;document.getElementById('nodes').checked=true;document.getElementById('detail').textContent=`道路节点 ${id}\n${D.nodes[id][2]}\n经度 ${cx}\n纬度 ${cy}`;draw()}else document.getElementById('detail').textContent='节点编号不存在';return}const s=D.signals.find(s=>s.id===q);if(s){cx=s.lon;cy=s.lat;scale=25000;choose(s)}else document.getElementById('detail').textContent='未找到该现役主交通信号灯编号。'};
canvas.onpointerdown=e=>{canvas.setPointerCapture(e.pointerId);drag=[e.offsetX,e.offsetY,cx,cy];moved=false};canvas.onpointermove=e=>{if(!drag)return;let dx=e.offsetX-drag[0],dy=e.offsetY-drag[1];if(Math.abs(dx)+Math.abs(dy)>4)moved=true;cx=drag[2]-dx/(scale*cos);cy=drag[3]+dy/scale;draw()};canvas.onpointerup=e=>{if(!moved){let best=null,d=13;for(const s of D.signals){if(!document.getElementById(s.distance<=200?'good':'bad').checked)continue;const p=xy(s.lon,s.lat),v=Math.hypot(p[0]-e.offsetX,p[1]-e.offsetY);if(v<d){d=v;best=s}}if(best)choose(best)}drag=null};canvas.onwheel=e=>{e.preventDefault();const lon=cx+(e.offsetX-W/2)/(scale*cos),lat=cy-(e.offsetY-H/2)/scale;scale*=Math.exp(-e.deltaY*.001);cx=lon-(e.offsetX-W/2)/(scale*cos);cy=lat+(e.offsetY-H/2)/scale;draw()};document.getElementById('counts').textContent=`${D.signals.length} 个现役主交通信号灯 · ${D.signals.filter(s=>s.road_node).length} 个道路候选`;resize();fit();
</script></html>'''
(ROOT/'reports/geographic_preview.html').write_text(html.replace('__DATA__',json.dumps(data,ensure_ascii=False).replace('<','\\u003c')),encoding='utf-8')
print(ROOT/'reports/geographic_preview.html')
